### ISSUE TITLE
One-to-many appearance

### ISSUE THREAD

**Issue by XedinUnknown** [wpmetabox/mb-relationships#10]
Sometimes, there is a need to have a one-to-many (or many-to-one) relationship. I understand that all MetaBox relationships are many-to-many, and for querying that's OK. However, what is often important is to not let the user select more than one relationship. This could be easily solved through the UI, e.g. by always rendering exactly one field. This should be configurable, of course; perhaps another member for the `meta_box` index.

**Comment by rilwis** [comment]
This can be done using the `max_clone` parameter for `field`. Please see [the docs](https://docs.metabox.io/extensions/mb-relationships/#syntax) for details.
