### ISSUE TITLE
is there a way to count connected itens?

### ISSUE THREAD

**Issue by hgodinho** [wpmetabox/mb-relationships#20]
I am developing a theme using MB relationships and i want to know if theres a way to count the connected itens.
i.e: 
custom post type: author
custom post type: artwork
relationship: author_to_artwork

and echo this: Van Gogh have 913 paintings
is it possible in an archive page?

**Comment by rilwis** [comment]
You can [query connected posts](https://docs.metabox.io/extensions/mb-relationships/#working-with-an-archive-of-posts) and output `count( $post->connected )`.

**Comment by claytoncollie** [comment]
And what if you have multiple relationship metaboxes on a single object? Does the count from each metabox get combined into that single field?

**Comment by hgodinho** [comment]
thanks @rilwis!

**Comment by rilwis** [comment]
@claytoncollie Yes, if query multiple relationships (which has just been done in 62e0a47f62bdaf186498499fe0d5c9e15d4dbe58), the returned number is the total connected items.
