### ISSUE TITLE
Pagination on related posts query

### ISSUE THREAD

**Issue by hgodinho** [wpmetabox/mb-relationships#21]
On issue #20 I talked about two custom post-types that I created: authors and artworks.
Ive made a single-author template and then queried the relationships on artworks, but I couldnt get the pagination to work. Am I missing something?

The CPT declaration:
```
        register_post_type(
            'autores',
            array(
                'supports' => array(
                    'title',
                    'revisions',
                    'comments',
                ),
                'public' => true,
                'publicly_queryable' => true,
                'show_in_menu' => false,
                'has_archive' => true,
                'hierarchical' => true,
                'rewrite' => array(
                    'slug' => PLUGIN_SLUG . '/autor',
                    'with_front' => false,
                    'pages' => true,
                ),
            )
        );
```

The query:
```
$args = array(
    'post_type' => 'obras',
    'post_status' => 'any',
    'relationship' => array(
        'id' => 'obras_to_autores',
        'to' => $post->ID,
    ),
    'posts_per_page' => 6,
    'paged' => 0,
);
$connected = new WP_Query($args);
```

When I click the number of the pagination menu, it redirects to the same page

**Comment by rilwis** [comment]
Hi @hgodinho ,

The URL you're viewing only works for default WordPress's pagination. If you want to paginate the related items, then you have to do that on your own by: setting up a custom query var and parse that query var and pass to the relationship query.
