### ISSUE TITLE
Data not saving -> CREATE TABLE problems 

### ISSUE THREAD

**Issue by clebuchegger** [wpmetabox/mb-relationships#29]
hi,

please adjust your create tables code to the official guide:
https://codex.wordpress.org/Creating_Tables_with_Plugins

In some cases the collate can be empty, failing to create the table, thus not saving:
https://github.com/wpmetabox/mb-relationships/blob/58df92c68ad9b6ec1b982a0a4332d3d42053d4dd/inc/database/table.php#L27-L47

the get_charset_collate() takes care of this:

$charset_collate = $wpdb->get_charset_collate();
// Create new table.
$sql = "
		CREATE TABLE {$wpdb->mb_relationships} (
				`ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				`from` bigint(20) unsigned NOT NULL,
				`to` bigint(20) unsigned NOT NULL,
				`type` varchar(44) NOT NULL default '',
				`order_from` bigint(20) unsigned NOT NULL,
				`order_to` bigint(20) unsigned NOT NULL,
				PRIMARY KEY  (`ID`),
				KEY `from` (`from`),
				KEY `to` (`to`),
				KEY `type` (`type`)
			) $charset_collate;";

cheers!

**Comment by rilwis** [comment]
Thanks for your feedback. The fix has been just committed.
