### ISSUE TITLE
Basic post type relationship dont work.

### ISSUE THREAD

**Issue by hexcross** [wpmetabox/mb-relationships#3]
Hi, Im trying MB relationships plugin but after many hours I still cant use it.  In WP-admin is everything OK, but when I try to query posts from template its failed. Can you take look at this bug? Its really flustrating and usseless now.

Init:

```php
add_action( 'mb_relationships_init', function() {
    MB_Relationships_API::register( array(
        'id'   => 'articlebanner_to_articles',
        'from'   => 'm_articlebanner',
        'to'   => 'blog_article'
    ) );
} );
```

Query function:

```php
function getPostBanner(){
	$connected = new WP_Query( array(
		'post_type' => 'm_articlebanner',
	  'relationship' => array(
	      'id' => 'articlebanner_to_articles',
	      'to' => 3798,
	  ),
	  'nopaging' => true
	) );

	return $connected;
}
```

DB records:
![image](https://user-images.githubusercontent.com/1681339/39624540-05ec4464-4f9a-11e8-86d3-ec61692bd31b.png)

Thanks for help.

**Comment by rilwis** [comment]
Let's close this ticket in favor of discussion in the [support forum](https://metabox.io/support/topic/basic-post-type-relationship-dont-work/). It's hard to track in both places.
