### ISSUE TITLE
Feature Request: Registration hook for external integration plugin

### ISSUE THREAD

**Issue by hsimah** [wpmetabox/mb-relationships#31]
I've been working on an integration plugin for MB Relationships and WPGraphQL.

What would be nice is a post-registration hook in this plugin, so once a user has called the API's register function I can execute the WPGraphQL registration. My plugin would also add an additional field to the settings (`graphql_name` or similar), but this can be ignored by MBR.

The flow would look like this:
- user registers an MBR
- MBR calls action with user supplied settings
- Integration plugin registers GraphQL connection for the relationship
  - this has two requirements: the types have `show_in_graphql => true` and have supplied `graphql_name` as part of the `to` and `from` settings
- Query the graph and the relationship would appear in the schema allowing consumers to retrieve related posts

**Comment by rilwis** [comment]
Hi @hsimah,

Thanks a lot for your contribution. I've merged your PR.
