### ISSUE TITLE
Reciprocal relationships do not follow the order of the admin

### ISSUE THREAD

**Issue by rodrigo-arias** [wpmetabox/mb-relationships#35]
Hi Anh,

I created a [ticket](https://metabox.io/?post_type=topic&p=19168) in the metabox forum but I don't see it as published.

When I get the reciprocal relationship fields they seem sorted by _post_date_ and they no longer follow the admin order.

```
new WP_Query(
    array(
        'relationship'   => array(
            'id'   => 'posts_to_posts',
            'to' => get_the_ID(),
        ),
        'nopaging'     => true,
    )
);
```

[Admin](https://imgur.com/JDEna1e)
[Frontend](https://imgur.com/gP0EBwP)

I’m not sure if there are any additional parameters that I need to add to get the administrator order. Thank you!

**Comment by claytoncollie** [comment]
I can confirm this issue. An on reciprocal relationships it is happening too. The order set in the admin is not what is shown on the frontend.

**Comment by rodrigo-arias** [comment]
I close this issue since we are following it in #36
