### ISSUE TITLE
MB_Relationships_API::get_connected() not returning data when CPT is set to exclude from search

### ISSUE THREAD

**Issue by badabingbreda** [wpmetabox/mb-relationships#39]
Whenever the Custom Post Types is set to exclude from search, it will be excluded from the results in the get_connected() return-data. This seems to be per WP-settings, when post_type == 'any' applies.

However, one might not want that CPT to appear within search results on frontend.

**Comment by rilwis** [comment]
Related issue #9.

**Comment by v-marinkov** [comment]
@rilwis Has this really been fixed because I just experienced the same issue? Here is my support topic: https://metabox.io/support/topic/relationships-suddenly-stopped-working/
