### ISSUE TITLE
Add post_status next to post_title when not 'publish'

### ISSUE THREAD

**Issue by claytoncollie** [wpmetabox/mb-relationships#4]
Would be nice to show the post title with a (draft) or (private) next to it when applicable. Right now if a post is draft status, the select field shows the connection based on the database call but the placeholder text shows the default text of 'Select a ....'.  See my screenshot below.  Atlanta and San Diego are published but the middle on is a draft.

This is confusing and does not describe what is actually going to the end user.

![image](https://user-images.githubusercontent.com/4236538/42401984-defc7a42-813d-11e8-81a1-33263277ff33.png)

**Comment by rilwis** [comment]
Hi,

By default, the plugin shows only published posts. If you need to make connections with draft/private posts, then you can modify the query using the `query_args` for the `from` or `to` parameters in the relationship settings:

```php
'to' => array(
    'object_type' => 'post',
    'post_type' => 'post',
    'query_args' => array( 'post_status' => 'any' ),
    'meta_box' => (),
),
```

Then all posts will display in the dropdown as usual. No need to append (draft) or (private) text next to the title.

**Comment by claytoncollie** [comment]
Thanks for guidance! This will do the trick. :)
