### ISSUE TITLE
FEATURE REQUEST: collapse meta box on edit page load

### ISSUE THREAD

**Issue by claytoncollie** [wpmetabox/mb-relationships#5]
Thanks for adding this option in the main plugin. 

[https://github.com/wpmetabox/meta-box/commit/bc6cbdbf5869308c9d6d044a69139cae3ffdfad2](https://github.com/wpmetabox/meta-box/commit/bc6cbdbf5869308c9d6d044a69139cae3ffdfad2)

Can you add it to this extension as well?

**Comment by rilwis** [comment]
Added in 52028b22ecffe8673ad9fae26c39e9bea5ce56a3
