### ISSUE TITLE
Error when deleting post objects, relationships are not deleted

### ISSUE THREAD

**Issue by devnullroot** [wpmetabox/mb-relationships#54]
When deleting a (custom) post object, the following error is thrown:
`wpdb::prepare was called incorrectly. The query does not contain the correct number of placeholders (3) for the number of arguments passed (2).`

In consequence, no relationship is deleted from the db.

This originates from `storage-handler.php::delete_object_relationships`

As far as I can tell, depending on the value of `$target`, the parameter `$object_id` has to be passed as the forth argument again to `wpdb->prepare`.

The resulting code would look something like this:

```
protected function delete_object_relationships( $object_id, $type, $target ) {
	global $wpdb;
	$sql = $target
		? "DELETE FROM $wpdb->mb_relationships WHERE `type`=%s AND `$target`=%d"
		: "DELETE FROM $wpdb->mb_relationships WHERE `type`=%s AND (`from`=%d OR `to`=%d)";

        if ( $target ) {
            $wpdb->query(
    	        $wpdb->prepare(
    		    $sql,
    		    $type,
    		    $object_id
    	        )
    	    );
        } else {
            $wpdb->query(
                $wpdb->prepare(
                    $sql,
                    $type,
                    $object_id,
                    $object_id
                )
            );
        }
}
```
mb-relationships: 1.10.8
wordpress: 5.8

**Comment by rilwis** [comment]
Fixed in c262ef853d05288313e690266d9de3bd68ac7a49
