### ISSUE TITLE
 parse config does not have a way to update the link from the parameters

### ISSUE THREAD

**Issue by simongcc** [wpmetabox/mb-relationships#63]
Version 1.10.11

In the admin-columns.php, there is a parse_config method to take the config from the argument including the meta.
The current 'link' is static value instead of talking it from the parameters, I guess it is supposed to get the config from the meta value?
So that one could use "edit" instead of view.

```
private function parse_config( $side ) {
		$admin_column = $this->$side['admin_column'];
		$title        = $this->$side['meta_box']['title'];

		$config = array(
			'position' => '',
			'target'   => '',
			'title'    => $title,
			'link'     => 'view',
		);
// ...
```

So it is by design, according to the testing logic in post.php render_view method, there is possibility to use "edit" instead I think.
It could be something like,
```
// ...
               $admin_column = $this->$side['admin_column'];
		$title        = $this->$side['meta_box']['title'];
		$view        = $this->$side['meta_box']['view'];

              $config = array(
			'position' => '',
			'target'   => '',
			'title'    => $title,
			'link'     => $view,
		);

// ...
```
Is it correct?

**Comment by rilwis** [comment]
Hi @simongcc ,

Thanks for your feedback. The code in the plugin is correct. The `$config` is merged with user config [here](https://github.com/wpmetabox/mb-relationships/blob/bcf8efa6aabe28e05ac01d1a6097193123a86b1e/inc/relationship/admin-columns.php#L303).

To change the link type, you should specify admin column config as follow:

```php
'admin_column' => [
    'position' => 'after title',
    'title'    => 'Price',
    'link'     => 'edit',
],
```
