### ISSUE TITLE
Indirect variable access in PHP 5.x - Illegal string offset 'object_type' 

### ISSUE THREAD

**Issue by kuebel** [wpmetabox/mb-relationships#7]
Hi!

wp-content/plugins/mb-relationships/inc/class-mb-relationships-relationship.php

	public function get_object_type( $side ) {
		return $this->$side['object_type'];
	}

produces the warning "Illegal string offset 'object_type'" and should be changed to
return $this->{$side}['object_type'];
to work in older versions of PHP. (Sorry, incorrect title, I mixed it up)

**Comment by rilwis** [comment]
Thanks for your report. I've just fixed it!
