### ISSUE TITLE
Cannot query for posts excluded from search

### ISSUE THREAD

**Issue by XedinUnknown** [wpmetabox/mb-relationships#9]
## Symptom

When using a query such as below, no results are returned if the post type of the relationship was registered with `exclude_from_search` set to `true` (example taken from [docs](https://docs.metabox.io/extensions/mb-relationships/#shortcode)):

```php
$connected = new WP_Query( array(
    'relationship' => array(
        'id'   => 'posts_to_pages',
        'from' => get_the_ID(), // You can pass object ID or full object
    ),
    'nopaging'     => true,
) );
```

## Cause
The plugin [sets the `post_type` argument to `'any'`](https://github.com/wpmetabox/mb-relationships/blob/master/inc/query/class-mb-relationships-query-post.php#L52) for every post query which has the `relationship` argument. When `post_type` is set to `'any'`, according to [WP Codex](https://codex.wordpress.org/Class_Reference/WP_Query#Type_Parameters), post types that have `exclude_from_search` set to `true` will not be queried. In such cases, WordPress [explicitly excludes](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-query.php#L2353) posts that "shouldn't be searchable" from the list.

## Solution
Normally, it is possible to query "non-searchable" post types by explicitly specifying the post type. However, this plugin overwrites the `post_types` arg with `any`.

To solve this, modify the plugin to only set `post_types` to any if the argument isn't already present.

**Comment by rilwis** [comment]
I've just pushed a fix. Please check it.

Thanks a lot for your feedback.

**Comment by XedinUnknown** [comment]
Looks good, apart from [this](https://github.com/wpmetabox/mb-relationships/commit/faa50d85e8cf64fe55bcbe69d1b283ac1b67cb18#r30651887), which I'm unsure about.

**Comment by XedinUnknown** [comment]
Looks good now. However, probably not such a good idea to commit to `master` branch ;)

Thanks for the fix.
